# Generated by Django 5.2.12 on 2026-03-25 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_orphanageprofile_id_alter_societyprofile_id'),
        ('profiles', '0003_societyprofile_jenis_kelamin_and_more'),
    ]

    operations = [
    ]
