# Generated by Django 6.0.3 on 2026-03-16 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Society',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('sandi', models.CharField(max_length=128)),
                ('alamat', models.TextField(blank=True, null=True)),
                ('nama_pengguna', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
