# Generated by Django 5.2.12 on 2026-03-25 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_id'),
        ('accounts', '0003_pendingregistration_nomor_telepon'),
    ]

    operations = [
    ]
